// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/compose-share.tsx": () => import("../components/mockups/compose-share.tsx"),
  "./components/mockups/compose.tsx": () => import("../components/mockups/compose.tsx")
};
